#kubectl create secret generic mysql-root-pass --from-literal=password=YUIidhb667
#kubectl create secret generic mysql-user-pass --from-literal=username=kodekloud_pop --from-literal=password=BruCStnMT5
#kubectl create secret generic mysql-db-url --from-literal=database=kodekloud_db9

##to create Secret object in yaml file, apiVersion: v1
#kind: Secret
#metadata:
#  name: mysql-root-pass
#type: Opaque
#data:
#  password: #value must be converted to base64 with: echo -n "YUIidhb667" | base64 -w0
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 250Mi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  hostPath:
    path: "/var/lib/mysql"



---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 250Mi
  storageClassName: slow

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
        - name: mysql-pv
          persistentVolumeClaim:
            claimName: mysql-pv-claim

      containers:
        - name: mysql
          image: mysql
          volumeMounts:
          - name: mysql-pv
            mountPath: /var/lib/mysql
          ports:
          - containerPort: 3306
            name: mysql

          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name:  mysql-root-pass
                  key: password
                  optional: false # same as default; "mysql-root-pass" must exist
                                # and include a key named "password"
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-db-url
                  key: database
                  optional: false
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name:  mysql-user-pass
                  key: username
                  optional: false
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name:  mysql-user-pass
                  key: password
                  optional: false

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: NodePort
  selector:
    app: mysql
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 3306
      targetPort: 3306
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30007
